# name: Deploy to Azure Blob Storage

# on:
#   push:
#     branches:
#       - main  # or your default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Upload to Azure Blob Storage
#       uses: azure/CLI@v1
#       with:
#         inlineScript: |
#           az storage blob upload-batch \
#             --account-name swapro  \
#             --destination '$web' \
#             --source ./src \
#             --overwrite
#       env:
#         AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clear old files in $web
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob delete-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --source '$web'

    - name: Upload new frontend to $web
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --destination '$web' \
            --source ./src \
            --overwrite

